import { AGENTS } from '../utils/constants';

export default function LedgerExplorer({ ledgerEntries, selectedEntry, onSelectEntry }) {
  if (ledgerEntries.length === 0) {
    return (
      <div className="panel glass">
        <div className="panel-header">
          <span className="panel-title">📒 Truth Ledger</span>
          <span className="panel-badge">0 entries</span>
        </div>
        <div className="empty-state">
          <span className="empty-state-icon">🔗</span>
          <span className="empty-state-text">Genesis block awaiting first commit</span>
        </div>
      </div>
    );
  }

  return (
    <div className="panel glass">
      <div className="panel-header">
        <span className="panel-title">📒 Truth Ledger</span>
        <span className="panel-badge">{ledgerEntries.length} entries</span>
      </div>
      <div style={{ marginBottom: 'var(--gap-sm)', fontSize: '0.75rem', color: 'var(--text-tertiary)' }}>
        ℹ Click any block below to inspect the full data and reasoning generated by that agent.
      </div>
      <div className="ledger-chain">
        {ledgerEntries.map((entry, i) => {
          const agent = AGENTS[entry.agentId] || {};
          const isSelected = selectedEntry?.entryHash === entry.entryHash;

          return (
            <div key={i}>
              {i > 0 && (
                <div className="ledger-link">
                  <div className="ledger-link-line" />
                </div>
              )}
              <div
                className={`ledger-block ${isSelected ? 'selected' : ''}`}
                onClick={() => onSelectEntry(entry)}
                style={{
                  borderLeftColor: agent.color || 'var(--glass-border)',
                  animationDelay: `${i * 0.15}s`,
                  cursor: 'pointer',
                  outline: isSelected ? `2px solid ${agent.color || 'var(--accent-cyan)'}` : 'none',
                  outlineOffset: '2px',
                  transform: isSelected ? 'translateX(4px)' : 'none',
                  background: isSelected ? 'rgba(255, 255, 255, 0.06)' : undefined,
                }}
              >
                <div className="ledger-block-header">
                  <span
                    className="ledger-agent-badge"
                    style={{
                      background: `${agent.color}20`,
                      color: agent.color,
                    }}
                  >
                    {agent.icon} {agent.name || entry.agentId}
                  </span>
                  <span className="verified-badge">✓ Verified</span>
                </div>
                <div className="ledger-summary">
                  Peer approvals: {entry.approvals} • Hash: <code style={{ fontFamily: 'var(--font-mono)', fontSize: '0.6rem' }}>{entry.entryHash}…</code>
                </div>
                <div className="ledger-hash" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span>prev: {entry.prevHash === 'GENESIS' ? '🌱 GENESIS' : `${entry.prevHash}…`}</span>
                  <span style={{ fontSize: '0.6rem', color: agent.color, opacity: 0.8 }}>Inspect ➜</span>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
